services:
  pg-data:
    image: postgres:18
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi_db
    volumes:
      - ny_taxi_db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - ny_taxi_db_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8085:80"
    networks:
      - ny_taxi_db_network

volumes:
  ny_taxi_db_data:
  pgadmin_data:


networks:
  ny_taxi_db_network:
